name: Run tests with Tox

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    with:
      python: "['3.10', '3.12']"
    needs:
      - call-inclusive-naming-check 
  
  validate-wheelhouse:
    uses: charmed-kubernetes/workflows/.github/workflows/validate-wheelhouse.yaml@main
    with:
      python: "['3.10', '3.12']" 
