name: Run tests with Tox

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run linter
        run: tox -e lint
      - name: Run Unit Tests
        run: tox -e unit  # Run tox using the version of Python in `PATH`
